# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  atomi.cloud/platform: sulfoxide
  atomi.cloud/service: iron
  atomi.cloud/module: operator
  atomi.cloud/layer: "1"


# -- KEDA Configuration. See [Helm Config for KEDA](https://github.com/kedacore/charts/tree/main/keda).
keda:
  prometheus:
    metricServer:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      enabled: true
      serviceMonitor:
        enabled: true
    webhooks:
      enabled: true
      serviceMonitor:
        enabled: true
  additionalAnnotations:
    <<: *tags
  additionalLabels:
    <<: *tags