# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  atomi.cloud/platform: sulfoxide
  atomi.cloud/service: iron
  atomi.cloud/layer: "1"

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

# -- KEDA Configuration. See [Helm Config for KEDA](https://github.com/kedacore/charts/tree/main/keda).
keda:
  topologySpreadConstraints:
    operator:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            <<: *tags
            atomi.cloud/module: operator
    metricsServer:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            <<: *tags
            atomi.cloud/module: metrics-adapter
    webhooks:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            <<: *tags
            atomi.cloud/module: webhooks
  prometheus:
    metricServer:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      enabled: true
      serviceMonitor:
        enabled: true
    webhooks:
      enabled: true
      serviceMonitor:
        enabled: true
  securityContext:
    <<: *securityContext
  podSecurityContext:
    <<: *podSecurityContext

  additionalAnnotations:
    <<: *tags
  additionalLabels:
    <<: *tags

  podLabels:
    keda:
      <<: *tags
      atomi.cloud/module: operator
    metricsAdapter:
      <<: *tags
      atomi.cloud/module: metrics-adapter
    webhooks:
      <<: *tags
      atomi.cloud/module: webhooks
  podAnnotations:
    keda:
      <<: *tags
      atomi.cloud/module: operator
    metricsAdapter:
      <<: *tags
      atomi.cloud/module: metrics-adapter
    webhooks:
      <<: *tags
      atomi.cloud/module: webhooks