version: "3"

env:
  RELEASE_NAME: sulfoxide-iron

includes:
  util: tasks/Taskfile.util.yaml
  pichu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: opal
  pichu:onyx:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: onyx
  pichu:ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pichu
      CLUSTER: ruby
  pikachu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pikachu
      CLUSTER: opal
  pikachu:onyx:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pikachu
      CLUSTER: onyx
  pikachu:ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: pikachu
      CLUSTER: ruby
  raichu:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: raichu
      CLUSTER: opal
  raichu:onyx:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: raichu
      CLUSTER: onyx
  raichu:ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: raichu
      CLUSTER: ruby
  entei:opal:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: entei
      CLUSTER: opal
  entei:onyx:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: entei
      CLUSTER: onyx
  entei:ruby:
    taskfile: tasks/Taskfile.cluster.yaml
    vars:
      LANDSCAPE: entei
      CLUSTER: ruby
tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  latest:
    desc: Get the latest version of KEDA
    cmds:
      - task: util:latest
        vars:
          REPO_NAME: keda
          REPO_URL: https://kedacore.github.io/charts
          CHART_NAME: keda
